### ISSUE TITLE
Document should be updated with mvnw command for Windows

### ISSUE THREAD

**Issue by deepalimayekar** [spring-petclinic/spring-framework-petclinic#11]
Please add windows command ./mvnw.cmd jetty:run-war from the main folder of the project.

**Comment by arey** [comment]
Thanks for your feedback @deepalimayekar . Could you please submit a Pull Request. 
Readme.md looks like OK for me:
```
git clone https://github.com/spring-petclinic/spring-framework-petclinic.git
cd spring-framework-petclinic
./mvnw jetty:run-war
```
