### ISSUE TITLE
Contribute to the project.

### ISSUE THREAD

**Issue by clun** [spring-petclinic/spring-framework-petclinic#28]
Can you please add me to the `spring-petclinic` organization please ?

I do have reactive (Spring Weblux implementation) which I will delegate permission but I must be part of the community to maintain it later. https://github.com/DataStax-Examples/spring-petclinic-reactive

Thank you in advance

**Comment by arey** [comment]
Hi Cedrik. I've added you as a `spring-petclinic` member.

Your reactive versions is a really great work. Well done. I don't know how permission degleation is working. I let you try. If you want, I can create a `spring-petclinic-reactive` repository. Let me know.

**Comment by clun** [comment]
I transfered the ownership of the project to the community here. 

I also want to contribute to others projects, I am amazed specially by the microservice one. Happy to be there

**Comment by arey** [comment]
I am really happy to welcome a new member to the community. 
We  keep maintaining 2 microservices fork:

- https://github.com/spring-petclinic/spring-petclinic-microservices
- https://github.com/spring-petclinic/spring-petclinic-cloud

Your contribution are welcome 👍
