### ISSUE TITLE
Main class not found

### ISSUE THREAD

**Issue by vaishalilambe** [spring-petclinic/spring-framework-petclinic#5]
Hi ,

I am new to spring framework and cloned your code. While running it on server it is giving me HTTP 404 . Can you please see 
<img width="918" alt="screen shot 2018-04-17 at 10 09 28 pm" src="https://user-images.githubusercontent.com/25044621/38907925-079d9a6c-428c-11e8-8645-bf1a159420f9.png">

**Comment by vaishalilambe** [comment]
Please reply asap. Its urgent!

**Comment by zirconias** [comment]
just built the project and deployed it to tomcat 9,   it's working fine.

**Comment by vaishalilambe** [comment]
I mean I am getting this error after running on tomcat 9can you please elaborate steps

**Comment by arey** [comment]
Hoi @vaishalilambe, do you have configure the context path with /petclinic?

**Comment by vaishalilambe** [comment]
Nope I didn’t configure it is taking that by default I am trying to figure
out but not able to find where it is

**Comment by vaishalilambe** [comment]
Just downloaded the project, click run on server -> tomcat 9, and it opens this page. Please guide me I am not able to figure it out

**Comment by vaishalilambe** [comment]
I removed that context root and just replaced with "/" still doesn't work

**Comment by vaishalilambe** [comment]
BTW I am running it from STS

**Comment by arey** [comment]
Could you please give us your stackstrace?

**Comment by arey** [comment]
@vaishalilambe could you try to ```git pull ``` then to redeploy Petclinic into Tomcat 9?
I've fixed the issue between Java 9 and JAXB (see https://stackoverflow.com/questions/43574426/how-to-resolve-java-lang-noclassdeffounderror-javax-xml-bind-jaxbexception-in-j)

**Comment by vaishalilambe** [comment]
I am using Java 8.

I need below help from you
use tomcat9, . 
I am not able to see formatting for pages when I run my application PFA screenshot. Please provide me suggestions asap.

Also steps to achieve mysql connectivity as I am not connecting with my credentials to mysql
<img width="1410" alt="screen shot 2018-04-21 at 9 53 23 pm" src="https://user-images.githubusercontent.com/25044621/39090478-956470da-45ae-11e8-9482-7e2a4db261c0.png">

**Comment by arey** [comment]
Sorry but your screenshot does not look like the Spring Framework Petclinic one's.
Do you have any startup log?

**Comment by vaishalilambe** [comment]
It is spring pet clinic I just added additional screens to it. I will run
and provide you additional info in a while. I need input from you on data
base connectivity. I have MySQL workbench installed on my system .what
modifications I need to do to achieve database connectivity with my
database

**Comment by arey** [comment]
The readme gives you some information to run with a MySQL database insteaf of the HSQL default one: https://github.com/spring-petclinic/spring-framework-petclinic/blob/master/readme.md

**Comment by vaishalilambe** [comment]
So for my local database what change I need to do as in Pom .xml it refers
to jdbc url of spring

**Comment by arey** [comment]
Yes, you have to add the mysql JDBC driver and configure the ```data-access.properties```.

**Comment by vaishalilambe** [comment]
Can you please elaborate more . I am completely new to this and not able to
understand.

**Comment by arey** [comment]
Should be fixed. Please reopen this issue if the problem persists.
