### ISSUE TITLE
Use Spring Data JDBC

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-framework-petclinic#7]
We could add a fourth implementation of the DAO layer with Spring Data JDBC
https://projects.spring.io/spring-data-jdbc/

**Comment by maciejwalkowiak** [comment]
Hey @arey. I developed Spring Data JDBC version of PetClinic - https://github.com/maciejwalkowiak/spring-petclinic-data-jdbc.

Would you like to move it into the `spring-petclinic` organisation?

**Comment by arey** [comment]
Hi @maciejwalkowiak. Thanks for your proposal. I had a look to your Spring Data JDBC version of Petclinic and you've done a great job.

By reading your code and the  https://spring.io/blog/2018/09/24/spring-data-jdbc-references-and-aggregates blog post, implementing Spring Data JDBC repositories requires to split Many-to-One and Many-to-Many relationship. Thus I suppose we could not add a fourth DAO implementation in the `spring-framework-petclinic`version. So I'm aware to create a new repo in the `spring-petclinic` organisation.  Thanks a lot.

**Comment by maciejwalkowiak** [comment]
Thanks for quick reply and invitation!

> By reading your code and the https://spring.io/blog/2018/09/24/spring-data-jdbc-references-and-aggregates blog post, implementing Spring Data JDBC repositories requires to split Many-to-One and Many-to-Many relationship. Thus I suppose we could not add a fourth DAO implementation in the spring-framework-petclinicversion. So I'm aware to create a new repo in the spring-petclinic organisation. Thanks a lot.

Indeed, I had to modify the model a bit to make it work - separate repository is the way to go.

> By the way, you've started from the official version https://github.com/spring-projects/spring-petclinic powered by Spring Boot (and not the https://github.com/spring-petclinic/spring-framework-petclinic/ based on the Spring Framework)

That's on purpose, as far as I can see most forks are Boot-based. Do you prefer to base it on plain Spring Framework? 

Regarding readme - roger that 👍

**Comment by maciejwalkowiak** [comment]
Although I am in the org, I don't have permissions to push to `spring-petclinic-data-jdbc`:

```
~ git push petclinic master
remote: Permission to spring-petclinic/spring-petclinic-data-jdbc.git denied to maciejwalkowiak.
fatal: unable to access 'https://github.com/spring-petclinic/spring-petclinic-data-jdbc.git/': The requested URL returned error: 403
```

**Comment by arey** [comment]
Could you retry please? I gave you admin rights.

**Comment by arey** [comment]
Thanks a lot. I've twitted the news. I suppose we could close this issue.
