### ISSUE TITLE
Migrate from JSP to Thymeleaf

### ISSUE THREAD

**Issue by arey** [spring-petclinic/spring-framework-petclinic#79]
Consider to use Thymeleaf as template engine as https://github.com/spring-projects/spring-petclinic 
Not realy sure about this choice.
JSP pages are working and the `spring-framework-petlinic` repository is the only one that using JSP.

**Comment by MarianConstantinMarica** [comment]
Can I work on this issue?

**Comment by arey** [comment]
Hi Marian-Constanti. I'm definitively not sure about this choice. As long as JSP pages are supported by Spring Framework, I think we can continue with it. Il will close this issue.
I invite you to look at the open issues in the other repositories of https://github.com/spring-petclinic for your first contribution.
