### ISSUE TITLE
docker image install has buggered up menu

### ISSUE THREAD

**Issue by adbacker** [spring-petclinic/spring-framework-petclinic#81]
Repro steps:

install whatever the latest docker image is as of 22.12.16 using:
docker run -p 8080:8080 springcommunity/spring-framework-petclinic

image downloaded/started just fine.  However, viewing had a couple of issues:
in chrome, instead of the menu bar items or menu dropdown, there's a white box that says "toggle navigation" and no menu items.

In the dev console I see this:
Uncaught Error: Bootstrap's JavaScript requires jQ
<img width="815" alt="Screenshot 2022-12-26 at 1 15 58 PM" src="https://user-images.githubusercontent.com/1547674/209581109-2459a6d9-8bdd-42c3-ac05-2895373c3db6.png">
uery version 1.9.1 or higher, but lower than version 3
    at bootstrap.min.js:6:216
    at bootstrap.min.js:6:318
    
Firefox shows the menu items when the browser window is wide enough, and the app seems to work with them.  However, shrink the width to < 922px to show the menu button and the menu button is unresponsive.  

Firefox console also shows:

Uncaught Error: Bootstrap's JavaScript requires jQuery version 1.9.1 or higher, but lower than version 3
    <anonymous> http://localhost:8080/webjars/bootstrap/3.3.6/js/bootstrap.min.js:6
    <anonymous> http://localhost:8080/webjars/bootstrap/3.3.6/js/bootstrap.min.js:6
    

Cloning latest repo and building/running via maven worked fine.

**Comment by arey** [comment]
Hi @adbacker 
I've got the same issue. I will try to publish a more recent Docker image based on Boostrap 5 and without using jQuery.

**Comment by arey** [comment]
Could you please try the 6.0.3 image?
```
docker run -p 8080:8080 springcommunity/spring-framework-petclinic:6.0.3
```

**Comment by adbacker** [comment]
@arey , gave it a try and 6.0.3 looks good.  Thank you!
