### ISSUE TITLE
Spring framework 5.3.26 petclinic application and JDK21

### ISSUE THREAD

**Issue by kundana-boddeti** [spring-petclinic/spring-framework-petclinic#98]
I am trying to build and deploy petclinic application using JDK21.the deployment fails with java.lang.IllegalArgumentException: Unsupported class file major version 65.

**Comment by arey** [comment]
Hi @kundana-boddeti 
I never Java 11 with Petclinic. 
It looks like the project has been compiled with java 21 but the runtime does not support Java 11.
Did you have BUILD the project and RUN the project with the JDK 21 ?
Did you have the full stacktrace?

**Comment by kundana-boddeti** [comment]
yeah the run time is JDK21 and i have compiled and build the project using jdk21.
User defined listener org.springframework.web.context.ContextLoaderListener failed: org.springframework.beans.factory.BeanDefinitionStoreException: Failed to read candidate component class: URL [zip:/war/WEB-INF/lib/_wl_cls_gen.jar!/org/springframework/samples/petclinic/service/ClinicServiceImpl.class]; nested exception is org.springframework.core.NestedIOException: ASM ClassReader failed to parse class file - probably due to a new Java class file version that isn't supported yet: URL [zip:servers/admin/tmp/_WL_user/petclinic/66da6x/war/WEB-INF/lib/_wl_cls_gen.jar!/org/springframework/samples/petclinic/service/ClinicServiceImpl.class]; nested exception is java.lang.IllegalArgumentException: Unsupported class file major version 65.

**Comment by arey** [comment]
On Windows, I've downloaded the last OpenJDK 21 release candidate (build 35) from then Oracle website: https://jdk.java.net/21/

I've cloned the repo then executed the `mvn jetty:run` command line and the application is working
```
[INFO] jetty-11.0.12; built: 2022-09-14T02:38:00.723Z; git: d5b8c29485f5f56a14be5f20c2ccce81b93c5555; jvm 21+35-2513
```
Could you please try the above command line?

**Comment by kundana-boddeti** [comment]
This is happening when we try to deploy on weblogic server

**Comment by arey** [comment]
Maybe your Weblogic server still do not support Java 21? Which version are you using? Did you try with a simple Hello Servlet compiled with Java 21 ? 
On Petclinic, could you test to upgrade the Spring Framework version from `6.0.9` to `6.0.11`?

**Comment by arey** [comment]
Any news?

**Comment by arey** [comment]
Spring Petclinic is now based on the Spring Framework 6.1.
The application build successful with the JDK Eclipse Adoptium  21.0.1+12-LTS and run on Tomcat 10.0.16
